# Generated by Django 3.0.5 on 2020-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True, verbose_name='Categoria')),
                ('cat_description', models.TextField(blank=True, db_column='CAT_DESCRIPTION', max_length=100, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Categorie',
                'db_table': 'Categories',
                'ordering': ['category'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id_value', models.AutoField(db_column='ID_Value', primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=100, null=True, verbose_name='Valore')),
                ('descrizione', models.TextField(blank=True, db_column='Descrizione', max_length=500, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Valori',
                'db_table': 'Values',
                'ordering': ['id_value'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('atk_description', models.TextField(blank=True, db_column='ATK_Description', max_length=500, null=True, verbose_name='Descrizione')),
                ('correlazione', models.ManyToManyField(to='attack.Attacks')),
                ('valori_categoria', models.ManyToManyField(to='attack.Values')),
            ],
            options={
                'verbose_name_plural': 'Attacchi',
                'db_table': 'Attacks',
                'ordering': ['name'],
            },
        ),
    ]
