# Generated by Django 3.0.5 on 2020-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ['id_value'], 'verbose_name_plural': 'Valori'},
        ),
        migrations.AlterField(
            model_name='attacks',
            name='correlazione',
            field=models.ManyToManyField(blank=True, to='attack.Attacks'),
        ),
        migrations.AlterField(
            model_name='attacks',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
