# Generated by Django 3.0.5 on 2020-05-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0002_auto_20200525_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, verbose_name='Nome alternativo')),
            ],
            options={
                'verbose_name_plural': 'Attacchi',
                'db_table': 'Names',
                'ordering': ['name'],
            },
        ),
    ]
